# this for local
redirectUri: http://localhost:8080/oauth2callback

server:
  connection-timeout: 60000 
  port: 8080   
# this for production
# redirectUri: https://my-project-204113.appspot.com/oauth2callback

spring:
  application:
    name: GoogleCloudDemo
    
#feign:
 # hystrix: 
#    enabled: true